name: Build Docker for LATEST

on:
  schedule:
    - cron: '30 2 * * *'  
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  push_to_registry:
    name: push docker image to hub
    runs-on: ubuntu-latest
    steps:
      - name: check repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push multi-platform latest
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            pokys/365-epg-docker:latest
          platforms: linux/amd64,linux/arm64
